version: "3"
services:

  storage:
    image: mongo:latest
    volumes:
      - ./internal/testdata/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=scimd

  scimd:
    build: .
    ports:
      - "8787:8787"
    depends_on:
      - storage
    volumes:
      - ./setting:/setting
    environment:
      - SCIMD_PORT=8787
      - SCIMD_STORAGE_HOST=storage
      - SCIMD_STORAGE_NAME=scimd
      - SCIMD_CONFIG=setting
    command: --debug --service-provider-config=setting/service_provider_config.json