version: "3"
services:

  storage:
    image: mongo:latest
    volumes:
      - ./internal/testdata/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=scim2

  scimd:
    build: .
    ports:
      - "8787:8787"
    depends_on:
      - storage
    environment:
      - SCIMD_PORT=8787
      - SCIMD_STORAGE_HOST=storage
      - SCIMD_STORAGE_NAME=scim2