// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package core

import (
	"encoding/json"
	"errors"
	"io/ioutil"
	"sync"
)

type repositorySchema struct {
	items map[string]Schema
	mu    sync.RWMutex
}

// SchemaRepository is the ...
type SchemaRepository interface {
	Get(key string) *Schema
	Add(filename string) (Schema, error)
}

func (repo *repositorySchema) Get(key string) *Schema {
	repo.mu.RLock()
	defer repo.mu.RUnlock()
	if item, ok := repo.items[key]; ok {
		return &item
	}
	return nil
}

func (repo *repositorySchema) Add(filename string) (Schema, error) {
	var data Schema

	bytes, err := ioutil.ReadFile(filename)
	if err != nil {
		return data, err
	}
	err = json.Unmarshal(bytes, &data)
	if err != nil {
		return data, err
	}

	repo.mu.Lock()
	defer repo.mu.Unlock()

	var id string
	if id = interface{}(data).(Identifiable).GetIdentifier(); id == "" {
		return data, errors.New("missing identifier")
	}

	repo.items[id] = data

	return data, nil
}

var (
	repoSchema *repositorySchema
	onceSchema sync.Once
)

// GetSchemaRepository is a singleton repository for core schemas
func GetSchemaRepository() SchemaRepository {
	onceSchema.Do(func() {
		repoSchema = &repositorySchema{
			items: make(map[string]Schema),
		}
	})

	return repoSchema
}
