// Code generated by "stringer -type AuthenticationScheme auth_schemes.go"; DO NOT EDIT.

package server

import "strconv"

const _AuthenticationScheme_name = "OAuthOAuth2OAuthBearerTokenHTTPBasicHTTPDigest"

var _AuthenticationScheme_index = [...]uint8{0, 5, 11, 27, 36, 46}

func (i AuthenticationScheme) String() string {
	if i < 0 || i >= AuthenticationScheme(len(_AuthenticationScheme_index)-1) {
		return "AuthenticationScheme(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AuthenticationScheme_name[_AuthenticationScheme_index[i]:_AuthenticationScheme_index[i+1]]
}
